---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# About

This repo contains R code for generating the ACA premium caps. 

- Source: [26 U.S. Code ยง 36B - Refundable credit for coverage under a qualified health plan](https://www.law.cornell.edu/uscode/text/26/36B)
- Source: [KFF: Explaining Health Care Reform: Questions About Health Insurance Subsidies](http://kff.org/health-reform/issue-brief/explaining-health-care-reform-questions-about-health/)

# Havest the Applicable Percentages

```{r}
library(dplyr, warn.conflicts = FALSE)

xml2::read_html("https://www.law.cornell.edu/uscode/text/26/36B") %>% 
  rvest::html_table() %>% 
  .[[1]] %>% 
  pander::pander(split.cells = 25, caption = "Applicable Premium Percentage for Qualified Health Insurance Plans in the Exchange")
```

# Data

```{r premiumCap2014}
load("premiumCap2014.rda")
premiumCap2014

library(ggplot2)
ggplot(premiumCap2014, aes(x = fpg, y = cap)) +
  geom_line() +
  labs(x = "Federal Poverty Guidelines (%)",
       y = "Premium Cap (%)",
       title = "Premium Cap, by Income % Poverty in 2014")
```

